FROM jfloff/alpine-python:2.7-slim
RUN apk add --update --no-cache g++ gcc libxslt-dev python-dev \
    && pip --no-cache-dir install pyyaml lxml numpy textblob tweepy requests pymongo
ADD *.py /opt/iris/
CMD ["./opt/iris/iris.py", "xlm"]