xlm:
  symbol: XLMETH
  email:
    domain: cointler.com
    username: xlm
    password: yb^28dJC?3bY
  twitter:
    hashtags:
      - xlm
    timelines:
      - StellarLumens
      - StellarOrg

nuls:
  symbol: NULSETH
  email:
    domain: cointler.com
    username: nuls
    password: yb^28dJC?3bY
  twitter:
    hashtags:
      - xlm
    timelines:
      - StellarLumens
      - StellarOrg