version: '3'
services:
  iris:
    image: iris
    volumes:
      - ./config:/config:ro
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
  hephaestus:
    image: hephaestus
    volumes:
      - ./config:/config:ro
      - ./data/nn:/data:rw
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=./db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db:rw
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
