version: '3'
services:
  data-fetcher:
    image: data-fetcher
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
  data-distributor:
    image: data-distributor
    volumes:
      - ./config:/config:ro
      - ./data/nn:/data:rw
    environment:
      - PYTHONUNBUFFERED=1
  price-predictor:
    image: price-predictor
    volumes:
      - ./config:/config:ro
      - ./data:/data:rw
    depends_on:
      - data-distributor
    environment:
      - PYTHONUNBUFFERED=1
  decision-maker:
    image: decision-maker
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
  stock-manager:
    image: stock-manager
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
  manager:
    image: manager
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:5000
