version: '3'
services:
  data-fetcher:
    image: data-fetcher
    volumes:
      - ./config:/config:ro
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
  data-distributor:
    image: data-distributor
    volumes:
      - ./config:/config:ro
      - ./data/nn:/data:rw
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:5000
  price-predictor:
    image: price-predictor
    volumes:
      - ./config:/config:ro
    depends_on:
      - data-distributor
    environment:
      - PYTHONUNBUFFERED=1
  decision-maker:
    image: decision-maker
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
  stock-manager:
    image: stock-manager
    volumes:
      - ./config:/config:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8081:5000
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=./db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db:rw
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
