email:
  domain: cointler.com
  server: mail.cointler.com
binance:
  url: https://api.binance.com/
  interval: 1m
  loss: 0.99 # 1% loss
database_dir: db/
mongodb:
  location: 46.101.17.4
twitter:
  consumer_key: 7nQ1evwDEcuI3x0OYItLhZO95
  consumer_secret: lboFeJtUxAwB9ySXwwkQm4G1jiFxZuOls6rApJKi22jeJZVDhR
  access_token_key: 953383048304824321-HEx0xWznySV0Ag1UDtEViSAlX5qyqXM
  access_token_secret: XqY68PTH7lCfvDsA73BB2X1Q2bwouoUmFTIfFZF0Dz1dG
neural_network:
  input: 5
  output: 2
  training_file: /data/training_data.npy
  model_file: model.ckpt
vm:
  hostname: 159.65.24.75
  username: root
  model_file: model.zip
url:
  data-distributor: http://data-distributor:5000
  stock-manager: http://stock-manager:5000
  data-fetcher: http://data-fetcher:5000
  decision-maker: http://decision-maker:5000
  price-predictor: http://price-predictor:5000
  stock-manager: http://stock-manager:5000
data-fetcher:
  klines: 30
data-distributor:
  interval: 600
price-predictor:
  interval: 30
decision-maker:
  interval: 30
  thresholds: 
    buy: 1.01
    sell: 0.99