email:
  domain: cointler.com
  server: mail.cointler.com
binance:
  url: https://api.binance.com/
  interval: 1m
database_dir: db/
mongodb:
  location: mongodb
twitter:
  consumer_key: 7nQ1evwDEcuI3x0OYItLhZO95
  consumer_secret: lboFeJtUxAwB9ySXwwkQm4G1jiFxZuOls6rApJKi22jeJZVDhR
  access_token_key: 953383048304824321-HEx0xWznySV0Ag1UDtEViSAlX5qyqXM
  access_token_secret: XqY68PTH7lCfvDsA73BB2X1Q2bwouoUmFTIfFZF0Dz1dG
neural_network:
  input: 5
  training_file: /data/training_data
  model_file: model.ckpt
digital_ocean:
  access_key: 6WUWESP2FU23T6KIP23V
  access_secret: mstF9pNXcEp+fpk4KcioeUPyeyIHUMxUndYN7JllOm4
  endpoint: https://ams3.digitaloceanspaces.com
  region: ams3
  space: whitewave
  model_file: model.zip
url:
  data-distributor: http://data-distributor:5000
  stock-manager: http://stock-manager:5000
data-fetcher:
  interval: 30
data-distributor:
  interval: 30
price-predictor:
  interval: 30
decision-maker:
  interval: 30